In [4]:
# Task 1.1: Basic Filtering

# Create a NumPy array ages with the following values: [25, 30, 18, 35, 22, 40, 17].

import numpy as np

a = np.array([25,30,18,35,22,40,17])
print(a)

# Use boolean indexing to create a new array adults containing only the ages that are 18 or older.

adults = a[a >= 18]
print(adults)

[25 30 18 35 22 40 17]
[25 30 18 35 22 40]


In [10]:
# Task 1.2: Filtering with Multiple Conditions

# Using the ages array again, find the ages that are strictly greater than 20 AND strictly less than 35.


age = np.array([15,20,25,27,28,30,35,40])
print(age)

b = age[(age > 20) & (age < 35)]
print(b)

# Store the result in a new array called young_adults

young_adults =  b
print(young_adults)

[15 20 25 27 28 30 35 40]
[25 27 28 30]
[25 27 28 30]
