In [24]:
# Q1 Task 1: Import the NumPy library and print its version.

import numpy as np

print(np.__version__)

2.3.5


In [25]:
# Q2 Task 2: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# Q3 Task 3: Generate a two-dimensional NumPy array with random values and print its shape and data type.

import numpy as np

arr2 = np.random.rand(2,3)
print(arr2)

print("Shape",arr2.shape)
print("Data type",arr2.dtype)


[[0.029568   0.37561254 0.04984597]
 [0.90733333 0.59336159 0.69398923]]
Shape (2, 3)
Data type float64


In [27]:
# Q4 Task 4: Create a NumPy array with 50 evenly spaced values between 0 and 10.

import numpy as np

arr = np.linspace(0,10,50)
print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [28]:
# Q5 Task 5: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.
import numpy as np

list1=[1,2,3]
list2=[4,5,6]

list_sum=list1 + list2
print("Python list",list_sum)
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

arr_sum= arr1 + arr2
print("Numpy list",arr_sum)

Python list [1, 2, 3, 4, 5, 6]
Numpy list [5 7 9]


In [29]:
# Q6 Task 6: Create a NumPy array of all zeros with a shape of (3, 4).

import numpy as np

val=np.zeros((3,4))
print(val)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
# Q7 Task 7: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

import numpy as np

one= np.ones((2,5),dtype=float)
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
# Q8 Task 8: Use arange() to create a NumPy array containing numbers from 10 to 50 with a step of 5.

import numpy as np
arr= np.linspace(10,50,5)
print(arr)

[10. 20. 30. 40. 50.]


In [40]:
# Q9 Task 9: Generate a 3x3 identity matrix using NumPy.

arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# Q10 Task 10: Create a 4x4 array filled with random integers between 1 and 20.

ww=np.random.randint(1,21,size=(4,4))
print(ww)

[[ 2 10 14 18]
 [20  5 10 20]
 [ 7  4  6 11]
 [13 13  3 15]]


In [43]:
# Q11 Task 11: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

arr= np.arange(1,16)
print(arr)

sliced = arr[3:9]
print(sliced)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[4 5 6 7 8 9]


In [3]:
# Q12 Task 12: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.
import numpy as np
val= np.arange(1,10).reshape(3,3)
print(val)

element=val[1,2]
print(element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [11]:
# Q13 Task 13: Slice a 4x4 array to extract the last two rows and the last two columns.

import numpy as np

data = np.arange(1,17).reshape(4,4)
print(data)

elements = data[-2,-2]
print(elements)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
11


In [14]:
# Q14 Task 14: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.
import numpy as np
obj = np.random.randint(10,50,size=(5,5))
print(obj)

obj[0]=100
print("\nAfter replacing first row at 100: ")
print(obj)

[[15 18 21 18 27]
 [18 29 12 18 27]
 [15 15 24 40 10]
 [42 32 47 20 35]
 [20 18 15 29 18]]

After replacing first row at 100: 
[[100 100 100 100 100]
 [ 18  29  12  18  27]
 [ 15  15  24  40  10]
 [ 42  32  47  20  35]
 [ 20  18  15  29  18]]


In [15]:
# Q15 Task 15: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

arr = np.arange(1,11)
print(arr)

filter = arr[arr <= 5]
print("filtered value: ",filter)

[ 1  2  3  4  5  6  7  8  9 10]
filtered value:  [1 2 3 4 5]
