In [6]:
###                                                                 1. Mathematical Operations

In [7]:
# Q1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

b = np.array([[10,11,12],
             [13,14,15],
             [16,17,18]])

print(a)
print(b)

print("\n Add:""\n",a + b,
      "\n substract:""\n",a - b,
      "\n multipution:""\n",a * b,
      "\n divied:""\n",a / b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]

 Add:
 [[11 13 15]
 [17 19 21]
 [23 25 27]] 
 substract:
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]] 
 multipution:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]] 
 divied:
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [8]:
# Q2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

import numpy as np

info = np.random.randint(1,101,size=10)
print(info)

print("Square root:""\n",np.sqrt(info),
      "\nExponential:""\n",np.exp(info),
      "\nlogarithmic:""\n",np.log(info))

[11  2 65 15  7 43 35 91 67 67]
Square root:
 [3.31662479 1.41421356 8.06225775 3.87298335 2.64575131 6.55743852
 5.91607978 9.53939201 8.18535277 8.18535277] 
Exponential:
 [5.98741417e+04 7.38905610e+00 1.69488924e+28 3.26901737e+06
 1.09663316e+03 4.72783947e+18 1.58601345e+15 3.31740010e+39
 1.25236317e+29 1.25236317e+29] 
logarithmic:
 [2.39789527 0.69314718 4.17438727 2.7080502  1.94591015 3.76120012
 3.55534806 4.51085951 4.20469262 4.20469262]


In [9]:
# Q3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

import numpy as np

arr = np.array([[10,20,30],
                [50,55,60]])
print(arr)
print("\nSin:""\n",np.sin(arr),
      "\nCos:""\n",np.cos(arr),
      "\nTan:""\n",np.tan(arr))

[[10 20 30]
 [50 55 60]]

Sin:
 [[-0.54402111  0.91294525 -0.98803162]
 [-0.26237485 -0.99975517 -0.30481062]] 
Cos:
 [[-0.83907153  0.40808206  0.15425145]
 [ 0.96496603  0.02212676 -0.95241298]] 
Tan:
 [[  0.64836083   2.23716094  -6.4053312 ]
 [ -0.27190061 -45.18308791   0.32004039]]


In [10]:
# Q4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

import numpy as np

arr = np.array([[10,20,30]])
print("Array:\n",arr)

mean = np.mean(arr)
std = np.std(arr)

normal_mean = (arr - mean) / std
print("\nNormal_mean:\n",normal_mean)
print("\nMean:\n",mean)
print("\nStd:\n",std)

Array:
 [[10 20 30]]

Normal_mean:
 [[-1.22474487  0.          1.22474487]]

Mean:
 20.0

Std:
 8.16496580927726


In [11]:
# Q5. Implement a function using NumPy that calculates the Euclidean distance between two points.

import numpy as np

p1 = np.array([10,20,50])
p2 = np.array([60,100,200])

dist = np.linalg.norm(p1-p2)
print(dist)

177.2004514666935


In [ ]:
###                                                          2. Combining and Splitting Arrays

In [13]:
# Q1. Create two 1D arrays and concatenate them horizontally and vertically.

import numpy as np

arra1 = ([500,400,300])
arra2 = ([200,800,1600])

horiz = np.concatenate((arra1,arra2))
print(horiz)

vertical = np.vstack((arra1,arra2))
print(vertical)


[ 500  400  300  200  800 1600]
[[ 500  400  300]
 [ 200  800 1600]]


In [26]:
# Q2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

import numpy as np

a = ([10,20,200])
b = ([200,300,400])

v = np.vstack((a,b))
print(v)
n= np.hstack((a,b))
print(n)

print(np.vsplit(v,2))
print(np.hsplit(n,2))

[[ 10  20 200]
 [200 300 400]]
[ 10  20 200 200 300 400]
[array([[ 10,  20, 200]]), array([[200, 300, 400]])]
[array([ 10,  20, 200]), array([200, 300, 400])]


In [37]:
# Q3. 3. Create a 2D array and split it into 4 equal sub-arrays.

import numpy as np

arra = np.array([[10,20,30,40],
         [44,55,66,77]])

v = np.vsplit(arra,2)
print(v)
b= np.hsplit(arra,2)
print(b)


[array([[10, 20, 30, 40]]), array([[44, 55, 66, 77]])]
[array([[10, 20],
       [44, 55]]), array([[30, 40],
       [66, 77]])]


In [18]:
# Q4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.
import numpy as np
a = np.array([[25,50],
              [75,100],
              [125,150]])

b = np.array([[15,30],
              [60,75],
              [105,120]])
# concantenate
print("concatenate")
print(np.concatenate((a,b)))
print("Joins arrays along an existing axis (does not create a new dimension")

# stack
print("stack")
print(np.stack((a,b)))
print("Stacks arrays along a new axis (creates an extra dimension). The input arrays must have the same shape")

# hstack
print("hstack")
print(np.hstack((a,b)))
print("Horizontal join only")

concatenate
[[ 25  50]
 [ 75 100]
 [125 150]
 [ 15  30]
 [ 60  75]
 [105 120]]
Joins arrays along an existing axis (does not create a new dimension
stack
[[[ 25  50]
  [ 75 100]
  [125 150]]

 [[ 15  30]
  [ 60  75]
  [105 120]]]
Stacks arrays along a new axis (creates an extra dimension). The input arrays must have the same shape
hstack
[[ 25  50  15  30]
 [ 75 100  60  75]
 [125 150 105 120]]
Horizontal join only


In [21]:
# Q5. Create a 3D array and flatten it, then reshape it back to its original shape.
import numpy as np
a = np.array([[[10,20,30],
       [40,50,60],
       [70,80,90]]])

fattered = a.flatten()
print(fattered)

reshaped = fattered.reshape(a.shape)
print(reshaped)

[10 20 30 40 50 60 70 80 90]
[[[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [ ]:
###                                                    3. Search, Sort, Aggregating/Statistical Functions

In [4]:
# Q1. Create a NumPy array and find the index of the maximum and minimum elements.

import numpy as np

arr = np.array([11,22,33,44,55])

max_arra = np.argmax(arr)
print(max_arra)

min_arra = np.argmin(arr)
print(min_arra)

4
0


In [23]:
# Q2. Sort a 2D array along different axes and display the result.

a = np.array([[11,44,55,33,22],
              [77,88,9,10,44]])
print(a)
sort = np.sort(a,axis = 0)
print("\n",sort)

sort1 = np.sort(a,axis = 1)
print("\n",sort1)

[[11 44 55 33 22]
 [77 88  9 10 44]]

 [[11 44  9 10 22]
 [77 88 55 33 44]]

 [[11 22 33 44 55]
 [ 9 10 44 77 88]]


In [35]:
# Q3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

arra = np.random.randint(1,11,10)
print(arra)

mean = np.mean(arra)
median = np.median(arra)
variance = np.var(arra)
sd = np.std(arra)

print("\n mean\n",mean,
      "\n median\n",median,
      "\n variance\n",variance,
      "\n std\n",sd)

[8 8 7 1 2 9 2 9 7 9]

 mean
 6.2 
 median
 7.5 
 variance
 9.360000000000001 
 std
 3.0594117081556713


In [43]:
# Q4. Use np.where to find all elements greater than a certain threshold in a given array.

import numpy as np

arra = np.array([[100,120,30],
                [50,40,30]])
threshold = 30
result = np.where(arra > threshold)
print(arra[result])


[100 120  50  40]


In [47]:
# Q5. Create a NumPy array and count how many elements are positive, negative, or zero.
import numpy as np

arra = np.array([[100,200,300],
                 [-111,-222,-333],
                 [0,0,0,]])

positive = np.sum(arra > 0)
negative = np.sum(arra < 0)
zero = np.sum(arra == 0)

print(positive)
print(negative)
print(zero)

3
3
3
